version: '3.8'

services:
  web:
    image: nginx:1.25-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html:ro
    networks:
      - backend
    depends_on:
      - php

  php:
    build: .
    container_name: owe
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - backend
    depends_on:
      - db

  db:
    image: mariadb:10.11
    container_name: owe_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: gbongbo
      MYSQL_DATABASE: owe_db
      MYSQL_USER: user
      MYSQL_PASSWORD: gbongbo_ede
    volumes:
      - db_data:/var/lib/mysql
      - ./schema:/docker-entrypoint-initdb.d:ro
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
